services:
  go_app:
    container_name: go_app
    build:
      context: .
    volumes:
      - .:/home/go/app
    environment:
      - PORT=80
    ports:
      - 80:80
    command: [ "tail", "-f", "/dev/null" ]
