apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1-go
  labels:
    app: test1-go
spec:
  selector:
    matchLabels:
      app: test1-go    
  replicas: 1 # Controlled by HPA
  template:
    metadata:
      labels:
        app: "test1-go"
    spec:
      containers:
        - name: test1-go
          image: "asoncs/test1_go:v8"

          resources:
            requests: # Minimum resources required for the container to run
              cpu: "0.05" # 50m = 5% of a vCPU core
              memory: 20Mi # 20 Megabytes
            limits: # Max resources the container can use
              cpu: "0.05" # 50m = 5% of a vCPU core
              memory: 25Mi # 25 Megabytes

          startupProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 3
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 3
            failureThreshold: 1
            # initialDelaySeconds: 15 # Commented because of startupProbe

          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1
            # initialDelaySeconds: 20 # Commented because of startupProbe

          envFrom:
            - configMapRef:
                name: test1-go-env
            - secretRef:
                name: test1-go-secret
          
          volumeMounts:
            - mountPath: "/home/go/app/myfamily"
              name: config
              readOnly: true
            - mountPath: "/home/go/app/pvc"
              name: test1-go-volume

      volumes:
        - name: test1-go-volume
          persistentVolumeClaim:
            claimName: test1-go-pvc

        - name: config
          configMap:
            name: configmap-family
            items:
            - key: members
              path: "family.txt"  
