apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1-go
  labels:
    app: test1-go
spec:
  selector:
    matchLabels:
      app: test1-go    
  replicas: 10
  template:
    metadata:
      labels:
        app: "test1-go"
    spec:
      containers:
        - name: test1-go
          image: "asoncs/test1_go:latest"

      #     resources:
      #       requests: 
      #         cpu: "0.05"
      #         memory: 20Mi
      #       limits:
      #         cpu: "0.05"
      #         memory: 25Mi

      #     startupProbe:
      #       httpGet:
      #         path: /healthz
      #         port: 80
      #       periodSeconds: 4
      #       failureThreshold: 30

      #     readinessProbe:
      #       httpGet:
      #         path: /healthz
      #         port: 80
      #       periodSeconds: 3
      #       failureThreshold: 1
      #       # initialDelaySeconds: 10

      #     livenessProbe:
      #       httpGet:
      #         path: /healthz
      #         port: 80
      #       periodSeconds: 5
      #       failureThreshold: 1
      #       timeoutSeconds: 1
      #       successThreshold: 1
      #       # initialDelaySeconds: 15

      #     envFrom:
      #       - configMapRef:
      #           name: test1-go-env
      #       - secretRef:
      #           name: test1-go-secret
          
      #     volumeMounts:
      #       - mountPath: "/go/myfamily"
      #         name: config
      #         readOnly: true
      #       - mountPath: "/go/pvc"
      #         name: test1-go-volume

      # volumes:
      #   - name: test1-go-volume
      #     persistentVolumeClaim:
      #       claimName: test1-go-pvc

      #   - name: config
      #     configMap:
      #       name: configmap-family
      #       items:
      #       - key: members
      #         path: "family.txt"  
